# GitHub Actions 工作流名称
name: China Mobile Auto Sign-in

# 工作流触发条件
on:
  # 1. 定时触发：使用 cron 表达式
  # 以下时间是 UTC 时间，'0 22 * * *' 对应北京时间 (UTC+8) 的早上 6:00
  schedule:
    - cron: '0 22 * * *'

  # 2. 手动触发：允许您在 GitHub Actions 页面手动运行此工作流
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run sign-in script
        env:
          CM_COOKIE: ${{ secrets.CM_COOKIE }}
        run: python main.py
